#!/bin/sh

#install iperf

sudo apt-get update
sudo apt-get install iperf -y

#install sockperf 

sudo apt-get install perl automake autoconf m4 libtool gcc g++ -y
cd ~
git clone https://github.com/Mellanox/sockperf.git
cd sockperf
./autogen.sh 
./configure 
make
sudo make install

#install kernel
cd /dev/
sudo apt-get install git build-essential kernel-package fakeroot libncurses5-dev libssl-dev ccache dpkg-dev xz-utils vim -y
sudo wget https://cdn.kernel.org/pub/linux/kernel/v4.x/testing/linux-4.9-rc2.tar.xz
sudo tar -xf linux-4.9-rc2.tar.xz
cd linux-4.9-rc2
cd net
cd sched
ls
echo "cd /dev/net/sched/"
